# Generated by Django 6.0.1 on 2026-02-27 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0006_alter_post_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='topic',
            new_name='category',
        ),
    ]
